default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instadrawapp_development

test:
  <<: *default
  database: instadrawapp_test

production:
  <<: *default
  database: instadrawapp_production
  username: instadrawapp
  password: <%= ENV['INSTADRAWAPP_DATABASE_PASSWORD'] %>
